### ISSUE TITLE
DTSU666 - missing total energy values

### ISSUE THREAD

**Issue by ciejj** [lmatula/ha_chint_pm#16]
First of all thank you for this plugin :)

After connecting and configuring DTSU666 (3P4W) the values of:  `Negative active total energy` and `Positive active total energy
` were stuck at 0.0 kwH.

I have done some digging, and changing the value in this [line](https://github.com/lmatula/ha_chint_pm/blob/main/custom_components/chint_pm/__init__.py#L431) to 0x401e fixes the issue

**Comment by lmatula** [comment]
Whitch version of DTSU666 do you have?
read the comment in code, i've tested two type of dtsu666, and is't containt valid data this register. maybe must create to third type of meter kind

**Comment by ciejj** [comment]
My version is: DTSU666 3x230/400V 5(80)A 4P 313280

**Comment by pvdeye** [comment]
I also have this problem?

**Comment by pvdeye** [comment]
Is there already a solution here?

**Comment by pvdeye** [comment]
maybee i find the Problem please change the adress to 101E then it must work

**Comment by thkn1973** [comment]
I also need the positive and negativ energy
comes there an update?
Thx

**Comment by maslyankov** [comment]
Issue is solved with above PR as soon as it is merged.

**Comment by ciejj** [comment]
@maslyankov I just checked that, and the newest version is not fixing it

**Comment by pela222** [comment]
hi, is update presented by @maslyankov solving the issue with Total energy values missing? If yes should I manually changed the files or will it be merged by @lmatula in main branch? If so when are you planning to do this. Thank you

**Comment by michaeldingbinSH** [comment]
The problem is still there, it's not fixed, I'm still reading the total energy as zero. If I change the register address to 0x401e, I can read the energy value, however it's constantly changing. When I try to get the energy assumed for current day, it's fluctuating rapidly. There is still something wrong.

**Comment by HellixFix** [comment]
_init_.py
there is different number in

            total = await client.read_holding_registers(
                address=0x4026, count=12, slave=unit_id

and 

            total = await client.read_holding_registers(
                address=0x101E, count=2, slave=unit_id

I think there should be **12** both
try it please

**Comment by maclun** [comment]
Have the same problem. Anyone has solved it yet?

**Comment by HellixFix** [comment]
> _init_.py there is different number in
> 
> ```
>         total = await client.read_holding_registers(
>             address=0x4026, count=12, slave=unit_id
> ```
> 
> and
> 
> ```
>         total = await client.read_holding_registers(
>             address=0x101E, count=2, slave=unit_id
> ```
> 
> I think there should be **12** both try it please

that solution works for me
using 0.0.8

**Comment by maclun** [comment]
Thanks a lot! it worked for me in 0.0.9.
